pipeline:
  docker:
    image: plugins/docker
    repo: captncraig/hscrds
    secrets: [ docker_username, docker_password ]
  deploy:
    image: appleboy/drone-ssh
    host: ${DEPLOY_HOST}
    username: ${DEPLOY_USER}
    secrets: [DEPLOY_HOST, DEPLOY_USER]